language: node_js

sudo: false

cache:
  directories:
    - node_modules

before_install:
 - "npm config set spin false"
 - "npm install -g npm@^2"

install:
 - npm install -g bower
 - npm install
 - bower install

script:
  - npm test

node_js:
  - "0.10"

deploy:
  provider: heroku
  api_key:
    secure: Bt7t26dMCqf7yXZPWZd/e6hz6N9Fxg83A34lC7sNTaLvIKnM+g54MHjOlIpnZ9LmN3S7/icg/X+twk2ebWPlc7THUWAaBkU5YjXpyNf9UhG30UG7Ihjgcbhn/Qh/Px8NQX5OFIUHTVoLdJGOj68/Czv+jHwpmFQHDoB1xCY2paE=
  app: webatrice
  on:
    repo: thomasjmwb/bbbbbbbbbbbbbbb
